--- #YAML:1.0
name:               Business-TNTPost-NL
version:            0.11
abstract:           Calculate Dutch (TNT Post) shipping costs
author:
    - M. Blom (blom@cpan.org)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Class::Accessor::Fast:  0
    List::Util:           0
    Test::Simple:         0.44
    YAML:                 0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
